# Generated by Django 6.0.2 on 2026-08-04 14:33

from django.db import migrations, models


def convert_month_codes(apps, schema_editor):
    month_codes = {
        "January": "01", "February": "02", "March": "03", "April": "04",
        "May": "05", "June": "06", "July": "07", "August": "08",
        "September": "09", "October": "10", "November": "11", "December": "12",
    }
    for model_name in ("In", "Out", "OutAllocation"):
        model = apps.get_model("data", model_name)
        for old_value, new_value in month_codes.items():
            model.objects.filter(month=old_value).update(month=new_value)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(convert_month_codes, noop),
        migrations.AlterField(
            model_name="in",
            name="month",
            field=models.CharField(
                choices=[
                    ("01", "Janvier"),
                    ("02", "Février"),
                    ("03", "Mars"),
                    ("04", "Avril"),
                    ("05", "Mai"),
                    ("06", "Juin"),
                    ("07", "Juillet"),
                    ("08", "Août"),
                    ("09", "Septembre"),
                    ("10", "Octobre"),
                    ("11", "Novembre"),
                    ("12", "Décembre"),
                ],
                editable=False,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="out",
            name="month",
            field=models.CharField(
                choices=[
                    ("01", "Janvier"),
                    ("02", "Février"),
                    ("03", "Mars"),
                    ("04", "Avril"),
                    ("05", "Mai"),
                    ("06", "Juin"),
                    ("07", "Juillet"),
                    ("08", "Août"),
                    ("09", "Septembre"),
                    ("10", "Octobre"),
                    ("11", "Novembre"),
                    ("12", "Décembre"),
                ],
                editable=False,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="outallocation",
            name="month",
            field=models.CharField(
                choices=[
                    ("01", "Janvier"),
                    ("02", "Février"),
                    ("03", "Mars"),
                    ("04", "Avril"),
                    ("05", "Mai"),
                    ("06", "Juin"),
                    ("07", "Juillet"),
                    ("08", "Août"),
                    ("09", "Septembre"),
                    ("10", "Octobre"),
                    ("11", "Novembre"),
                    ("12", "Décembre"),
                ],
                max_length=2,
            ),
        ),
    ]
