# Generated by Django 6.0.2 on 2026-08-04 14:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_in_month_alter_out_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="reference",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="article",
            name="reorder_level",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name="StockEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_entries",
                        to="data.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réapprovisionnement",
                "verbose_name_plural": "Réapprovisionnements",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
