# Generated by Django 6.0.2 on 2026-08-06 11:54

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_article_reference_article_reorder_level_stockentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField(unique=True)),
                ("week_end", models.DateField()),
                (
                    "income_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "expense_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "balance_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rapport hebdomadaire",
                "verbose_name_plural": "Rapports hebdomadaires",
                "ordering": ["-week_start"],
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nom de l'article"),
        ),
        migrations.AlterField(
            model_name="article",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantité en stock"),
        ),
        migrations.AlterField(
            model_name="article",
            name="reference",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Référence",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="reorder_level",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Niveau de réapprovisionnement"
            ),
        ),
    ]
