# Generated by Django 4.2.11 on 2026-08-20 18:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_weeklyreport_alter_article_name_alter_article_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="in",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Coût d’achat unitaire",
            ),
        ),
    ]
