# Generated by Django 6.0.2 on 2026-08-30 20:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_in_cost_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Quantité en stock",
            ),
        ),
        migrations.AlterField(
            model_name="in",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
